"""Factor formula → Python code. DSL interpreter with LLM fallback.

DSL operators (whitelisted):
  pct_change(s, n) · rolling_mean(s, n) · rolling_std(s, n) · rolling_sum(s, n)
  corr(a, b) · rank(s) · zscore(s)
  arithmetic: + - * / (unary negation)

Unknown operators fall back to LLM codegen (if llm_client provided).
Generated code is qtype-checked; qtype-dirty LLM output degrades to a
stub with NotImplementedError.
"""

from __future__ import annotations

import ast
import json
import textwrap

from replicalpha.core.models import CodegenMethod, CodegenResult
from replicalpha.vendored.paper2alpha.core.llm_client import LLMClient
from replicalpha.vendored.qtype.core.analyzer import QtypeAnalyzer

_WHITELIST_FUNCS = {
    "pct_change",
    "rolling_mean",
    "rolling_std",
    "rolling_sum",
    "corr",
    "rank",
    "zscore",
}
_WHITELIST_FIELDS = {"close", "open", "high", "low", "volume"}


class CodegenError(RuntimeError):
    """Raised when the DSL interpreter cannot translate the formula and no fallback is available."""


def generate_factor_code(
    formula: str,
    *,
    factor_name: str,
    params: dict[str, object],
    llm_client: LLMClient | None = None,
) -> CodegenResult:
    """Translate a factor formula to Python source + qtype-check it."""
    try:
        body = _dsl_translate(formula)
        source = _wrap_function(factor_name, params, body, method="dsl")
        passed, violations = _qtype_check(source)
        return CodegenResult(
            method="dsl",
            source_code=source,
            qtype_passed=passed,
            qtype_violations=violations,
        )
    except _UnsupportedDSLError as exc:
        if llm_client is None:
            raise CodegenError(f"unsupported formula for DSL and no LLM fallback: {exc}") from exc
        return _llm_fallback(formula, factor_name, params, llm_client)


class _UnsupportedDSLError(Exception):
    pass


def _dsl_translate(formula: str) -> str:
    tree = ast.parse(formula, mode="eval")
    return _emit(tree.body)


def _emit(node: ast.AST) -> str:
    if isinstance(node, ast.Constant):
        if isinstance(node.value, (int, float)):
            return str(node.value)
        raise _UnsupportedDSLError(f"unsupported constant {node.value!r}")
    if isinstance(node, ast.Name):
        if node.id in _WHITELIST_FIELDS:
            return f'_series("{node.id}")'
        raise _UnsupportedDSLError(f"unknown identifier {node.id!r}")
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
        return f"-({_emit(node.operand)})"
    if isinstance(node, ast.BinOp):
        left = _emit(node.left)
        right = _emit(node.right)
        op_map: dict[type, str] = {
            ast.Add: "+",
            ast.Sub: "-",
            ast.Mult: "*",
            ast.Div: "/",
        }
        for cls, sym in op_map.items():
            if isinstance(node.op, cls):
                return f"({left} {sym} {right})"
        raise _UnsupportedDSLError(f"unsupported operator {type(node.op).__name__}")
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
        if node.func.id not in _WHITELIST_FUNCS:
            raise _UnsupportedDSLError(f"unsupported function {node.func.id!r}")
        if node.keywords:
            raise _UnsupportedDSLError(f"keyword args not supported in DSL: {node.func.id!r}")
        args = [_emit(a) for a in node.args]
        return f"_{node.func.id}({', '.join(args)})"
    raise _UnsupportedDSLError(f"unsupported node {type(node).__name__}")


def _wrap_function(
    factor_name: str, params: dict[str, object], body: str, *, method: CodegenMethod
) -> str:
    raw_lookback = params.get("lookback", 20)
    lookback = int(raw_lookback) if isinstance(raw_lookback, (int, float, str)) else 20
    template = textwrap.dedent(
        '''
        """Factor: {factor_name} — generated by replicalpha ({method}).

        compute() returns a dict[ticker, value] for the given ``as_of`` date.
        """
        from __future__ import annotations

        from datetime import date, timedelta

        import pandas as pd


        FACTOR_NAME = {factor_name_literal}
        LOOKBACK = {lookback}


        def compute(adapter, as_of: date, universe: str = "") -> dict[str, float]:
            """Cross-sectional factor values at ``as_of``."""
            start = as_of - timedelta(days=LOOKBACK * 3)
            end = as_of

            def _series(field: str) -> pd.DataFrame:
                raw = adapter.get_price(field, start, end, universe)
                return pd.DataFrame({{t: pd.Series(v) for t, v in raw.items()}})

            def _pct_change(s: pd.DataFrame, n: int) -> pd.DataFrame:
                return s.pct_change(int(n))

            def _rolling_mean(s: pd.DataFrame, n: int) -> pd.DataFrame:
                return s.rolling(int(n)).mean()

            def _rolling_std(s: pd.DataFrame, n: int) -> pd.DataFrame:
                return s.rolling(int(n)).std()

            def _rolling_sum(s: pd.DataFrame, n: int) -> pd.DataFrame:
                return s.rolling(int(n)).sum()

            def _corr(a: pd.DataFrame, b: pd.DataFrame) -> pd.DataFrame:
                return a.rolling(LOOKBACK).corr(b)

            def _rank(s: pd.DataFrame) -> pd.DataFrame:
                return s.rank(axis=1, pct=True)

            def _zscore(s: pd.DataFrame) -> pd.DataFrame:
                return s.sub(s.mean(axis=1), axis=0).div(s.std(axis=1).replace(0, 1), axis=0)

            df = {body}
            last = df.dropna(how="all").iloc[-1] if not df.empty else pd.Series(dtype=float)
            return {{t: float(v) for t, v in last.items() if pd.notna(v)}}
        '''
    ).format(
        factor_name=factor_name,
        method=method,
        factor_name_literal=json.dumps(factor_name),
        lookback=lookback,
        body=body,
    )
    return template.lstrip()


def _qtype_check(source: str) -> tuple[bool, list[dict[str, object]]]:
    analyzer = QtypeAnalyzer()
    try:
        raw = analyzer.check_source(source)
    except SyntaxError as exc:
        return False, [{"rule": "SYNTAX", "severity": "error", "message": str(exc), "line": 0}]
    violations = [
        {
            "rule": v.rule_id,
            "severity": v.severity,
            "message": v.message,
            "line": v.line,
        }
        for v in raw
    ]
    passed = all(v["severity"] != "error" for v in violations)
    return passed, violations


_LLM_SYSTEM = (
    "You translate quant factor formulas to Python code. "
    "Return a json object with keys 'code' (str, a full module with a compute() function) "
    "and 'imports' (list[str], any extra imports beyond pandas). "
    "The compute function signature is: "
    'compute(adapter, as_of, universe="") -> dict[str, float]. '
    "Use only adapter.get_price and adapter.get_trading_days. Never use .shift(-n). "
    "Output only the json object."
)


def _llm_fallback(
    formula: str,
    factor_name: str,
    params: dict[str, object],
    llm: LLMClient,
) -> CodegenResult:
    user = (
        f"Formula: {formula}\nFactor name: {factor_name}\nParams: {json.dumps(params)}\n"
        "Return {code, imports} as JSON."
    )
    raw = llm.complete_json(system=_LLM_SYSTEM, user=user)
    try:
        payload = json.loads(raw)
        source = str(payload["code"])
    except (json.JSONDecodeError, KeyError, TypeError):
        return _stub_result(factor_name, params, note="LLM response not valid JSON")

    try:
        ast.parse(source)
    except SyntaxError as exc:
        return _stub_result(factor_name, params, note=f"LLM source parse error: {exc}")

    passed, violations = _qtype_check(source)
    if not passed:
        return _stub_result(factor_name, params, note=f"LLM source failed qtype: {violations}")
    return CodegenResult(
        method="llm",
        source_code=source,
        qtype_passed=True,
        qtype_violations=[],
    )


def _stub_result(factor_name: str, params: dict[str, object], *, note: str) -> CodegenResult:
    body = "pd.DataFrame()"
    source = _wrap_function(factor_name, params, body, method="stub")
    source = source.replace(
        'last = df.dropna(how="all").iloc[-1] if not df.empty else pd.Series(dtype=float)',
        'raise NotImplementedError("codegen produced a stub; see note in CodegenResult")',
    )
    return CodegenResult(
        method="stub",
        source_code=source,
        qtype_passed=False,
        qtype_violations=[],
        note=note,
    )
