"""Markdown report aggregator."""

from __future__ import annotations

import textwrap
import typing

from replicalpha.core.models import PipelineReport, PipelineStage
from replicalpha.vendored.paper2alpha.core.models import ResearchCard

_ALL_STAGES: frozenset[str] = frozenset(typing.get_args(PipelineStage))


def render_report(*, card: ResearchCard, report: PipelineReport) -> str:
    sections: list[str] = ["# Reproduction Report"]
    sections.append(_paper_section(card))
    sections.append(_codegen_section(report))
    sections.append(_backtest_section(report))
    sections.append(_red_team_section(report))
    sections.append(_reproducibility_section(report))
    sections.append(_footer(report))
    return "\n\n".join(sections).rstrip() + "\n"


def _paper_section(card: ResearchCard) -> str:
    factors_md = "\n".join(
        f"- **{f.name}** ({f.chinese_name}) — formula: `{f.formula}`" for f in card.factors
    )
    return textwrap.dedent(
        f"""\
        ## Paper

        - **Source**: {card.source}
        - **Factors claimed**:

        {factors_md}
        """
    ).rstrip()


def _codegen_section(report: PipelineReport) -> str:
    if report.codegen is None:
        return "## Factor Code\n\n(pending — codegen stage not completed)"
    cg = report.codegen
    status = "✅ qtype clean" if cg.qtype_passed else "⚠️ qtype violations present"
    note = f"\n\n*note*: {cg.note}" if cg.note else ""
    return textwrap.dedent(
        f"""\
        ## Factor Code

        Generated via **{cg.method}** ({status}).{note}

        ```python
        {cg.source_code.rstrip()}
        ```
        """
    ).rstrip()


def _backtest_section(report: PipelineReport) -> str:
    if report.backtest is None:
        return "## Backtest\n\n(pending — backtest stage not completed)"
    b = report.backtest
    return textwrap.dedent(
        f"""\
        ## Backtest

        - Period: `{b.start_date}` → `{b.end_date}`
        - IC mean: **{b.ic_mean:.4f}**  (std {b.ic_std:.4f})
        - Cumulative return: **{b.cumulative_return:+.2%}**
        - Max drawdown: **{b.max_drawdown:.2%}**
        - Annualized Sharpe: **{b.annualized_sharpe:.2f}**
        """
    ).rstrip()


def _red_team_section(report: PipelineReport) -> str:
    if not report.validator_findings:
        return "## Red Team\n\nNo findings — all 5 checks passed."
    lines = ["## Red Team"]
    for f in report.validator_findings:
        emoji = {"critical": "🔴", "warning": "🟡", "info": "🟢"}.get(f.severity, "⚪")
        lines.append(f"\n### {emoji} `{f.rule}` — {f.severity}")
        lines.append(f"\n{f.detail}")
        if f.suggestion:
            lines.append(f"\n*Suggestion*: {f.suggestion}")
    return "\n".join(lines).rstrip()


def _reproducibility_section(report: PipelineReport) -> str:
    if report.reproducibility is None:
        return "## Reproducibility\n\n(pending — reproducibility score not computed)"
    r = report.reproducibility
    claimed = f"{r.claimed_ic:.4f}" if r.claimed_ic is not None else "n/a"
    return textwrap.dedent(
        f"""\
        ## Reproducibility

        - Paper's claimed IC: **{claimed}**
        - Reproduced IC: **{r.reproduced_ic:.4f}**
        - Sign match: {r.sign_match:.0f}
        - Magnitude score: {r.magnitude_score:.2f}
        - **Final score**: {r.final_score:.2f}

        > {r.interpretation}
        """
    ).rstrip()


def _footer(report: PipelineReport) -> str:
    completed = ", ".join(report.completed_stages)
    status = "complete" if set(report.completed_stages) == _ALL_STAGES else "partial"
    return textwrap.dedent(
        f"""\
        ---

        *Run `{report.run_id}`; stages {status}: {completed}. Generated by replicalpha v0.1.*
        """
    ).rstrip()
